/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AaveLendingPoolCoreMockInterface extends utils.Interface {
  functions: {
    "getReserveATokenAddress(address)": FunctionFragment;
    "reserves(address)": FunctionFragment;
    "setReserveATokenAddress(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getReserveATokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "reserves", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setReserveATokenAddress",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReserveATokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReserveATokenAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AaveLendingPoolCoreMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AaveLendingPoolCoreMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReserveATokenAddress(
      _reserve: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    reserves(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    setReserveATokenAddress(
      _reserve: string,
      _aToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getReserveATokenAddress(
    _reserve: string,
    overrides?: CallOverrides
  ): Promise<string>;

  reserves(arg0: string, overrides?: CallOverrides): Promise<string>;

  setReserveATokenAddress(
    _reserve: string,
    _aToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getReserveATokenAddress(
      _reserve: string,
      overrides?: CallOverrides
    ): Promise<string>;

    reserves(arg0: string, overrides?: CallOverrides): Promise<string>;

    setReserveATokenAddress(
      _reserve: string,
      _aToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getReserveATokenAddress(
      _reserve: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reserves(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    setReserveATokenAddress(
      _reserve: string,
      _aToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReserveATokenAddress(
      _reserve: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserves(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setReserveATokenAddress(
      _reserve: string,
      _aToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
