/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface CompClaimAdapterInterface extends utils.Interface {
  functions: {
    "comptroller()": FunctionFragment;
    "getClaimCallData(address,address)": FunctionFragment;
    "getRewardsAmount(address,address)": FunctionFragment;
    "getTokenAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "comptroller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimCallData",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsAmount",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "comptroller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimCallData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CompClaimAdapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CompClaimAdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    comptroller(overrides?: CallOverrides): Promise<[string]>;

    getClaimCallData(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    getRewardsAmount(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenAddress(arg0: string, overrides?: CallOverrides): Promise<[string]>;
  };

  comptroller(overrides?: CallOverrides): Promise<string>;

  getClaimCallData(
    _setToken: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, string]>;

  getRewardsAmount(
    _setToken: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenAddress(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    comptroller(overrides?: CallOverrides): Promise<string>;

    getClaimCallData(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    getRewardsAmount(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenAddress(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    comptroller(overrides?: CallOverrides): Promise<BigNumber>;

    getClaimCallData(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardsAmount(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    comptroller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getClaimCallData(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardsAmount(
      _setToken: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
