/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface CTokenOracleInterface extends utils.Interface {
  functions: {
    "cToken()": FunctionFragment;
    "cTokenFullUnit()": FunctionFragment;
    "dataDescription()": FunctionFragment;
    "read()": FunctionFragment;
    "underlyingFullUnit()": FunctionFragment;
    "underlyingOracle()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "cToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cTokenFullUnit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataDescription",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "read", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlyingFullUnit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingOracle",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cTokenFullUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "underlyingFullUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingOracle",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CTokenOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CTokenOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cToken(overrides?: CallOverrides): Promise<[string]>;

    cTokenFullUnit(overrides?: CallOverrides): Promise<[BigNumber]>;

    dataDescription(overrides?: CallOverrides): Promise<[string]>;

    read(overrides?: CallOverrides): Promise<[BigNumber]>;

    underlyingFullUnit(overrides?: CallOverrides): Promise<[BigNumber]>;

    underlyingOracle(overrides?: CallOverrides): Promise<[string]>;
  };

  cToken(overrides?: CallOverrides): Promise<string>;

  cTokenFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

  dataDescription(overrides?: CallOverrides): Promise<string>;

  read(overrides?: CallOverrides): Promise<BigNumber>;

  underlyingFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

  underlyingOracle(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    cToken(overrides?: CallOverrides): Promise<string>;

    cTokenFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

    dataDescription(overrides?: CallOverrides): Promise<string>;

    read(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingOracle(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    cToken(overrides?: CallOverrides): Promise<BigNumber>;

    cTokenFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

    dataDescription(overrides?: CallOverrides): Promise<BigNumber>;

    read(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingFullUnit(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingOracle(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cTokenFullUnit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dataDescription(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    read(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingFullUnit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
