/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IDMMFactoryInterface extends utils.Interface {
  functions: {
    "allPools(uint256)": FunctionFragment;
    "allPoolsLength()": FunctionFragment;
    "createPool(address,address,uint32)": FunctionFragment;
    "feeToSetter()": FunctionFragment;
    "getFeeConfiguration()": FunctionFragment;
    "getPools(address,address)": FunctionFragment;
    "getUnamplifiedPool(address,address)": FunctionFragment;
    "isPool(address,address,address)": FunctionFragment;
    "setFeeConfiguration(address,uint16)": FunctionFragment;
    "setFeeToSetter(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allPoolsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeToSetter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPools",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnamplifiedPool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isPool",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfiguration",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeToSetter",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allPoolsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeToSetter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUnamplifiedPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeToSetter",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDMMFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDMMFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allPools(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { pool: string }>;

    allPoolsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    createPool(
      tokenA: string,
      tokenB: string,
      ampBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    feeToSetter(overrides?: CallOverrides): Promise<[string]>;

    getFeeConfiguration(
      overrides?: CallOverrides
    ): Promise<[string, number] & { feeTo: string; governmentFeeBps: number }>;

    getPools(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<[string[]] & { _tokenPools: string[] }>;

    getUnamplifiedPool(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isPool(
      token0: string,
      token1: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setFeeConfiguration(
      feeTo: string,
      governmentFeeBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeToSetter(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

  createPool(
    tokenA: string,
    tokenB: string,
    ampBps: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  feeToSetter(overrides?: CallOverrides): Promise<string>;

  getFeeConfiguration(
    overrides?: CallOverrides
  ): Promise<[string, number] & { feeTo: string; governmentFeeBps: number }>;

  getPools(
    token0: string,
    token1: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getUnamplifiedPool(
    token0: string,
    token1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  isPool(
    token0: string,
    token1: string,
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setFeeConfiguration(
    feeTo: string,
    governmentFeeBps: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeToSetter(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createPool(
      tokenA: string,
      tokenB: string,
      ampBps: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    feeToSetter(overrides?: CallOverrides): Promise<string>;

    getFeeConfiguration(
      overrides?: CallOverrides
    ): Promise<[string, number] & { feeTo: string; governmentFeeBps: number }>;

    getPools(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getUnamplifiedPool(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    isPool(
      token0: string,
      token1: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setFeeConfiguration(
      feeTo: string,
      governmentFeeBps: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeToSetter(arg0: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createPool(
      tokenA: string,
      tokenB: string,
      ampBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    feeToSetter(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getPools(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnamplifiedPool(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPool(
      token0: string,
      token1: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFeeConfiguration(
      feeTo: string,
      governmentFeeBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeToSetter(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allPools(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allPoolsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPool(
      tokenA: string,
      tokenB: string,
      ampBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    feeToSetter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPools(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnamplifiedPool(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPool(
      token0: string,
      token1: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFeeConfiguration(
      feeTo: string,
      governmentFeeBps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeToSetter(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
