/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface OneInchExchangeMockInterface extends utils.Interface {
  functions: {
    "addSetTokenAddress(address)": FunctionFragment;
    "mockReceiveAmount()": FunctionFragment;
    "mockReceiveToken()": FunctionFragment;
    "mockSendAmount()": FunctionFragment;
    "mockSendToken()": FunctionFragment;
    "setTokenAddress()": FunctionFragment;
    "swap(address,address,uint256,uint256,uint256,address,address[],bytes,uint256[],uint256[])": FunctionFragment;
    "updateReceiveAmount(uint256)": FunctionFragment;
    "updateSendAmount(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addSetTokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mockReceiveAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockReceiveToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockSendAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockSendToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string[],
      BytesLike,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReceiveAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSendAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSetTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockReceiveAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockReceiveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockSendAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockSendToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReceiveAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSendAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OneInchExchangeMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OneInchExchangeMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSetTokenAddress(
      _setTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockReceiveAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    mockReceiveToken(overrides?: CallOverrides): Promise<[string]>;

    mockSendAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    mockSendToken(overrides?: CallOverrides): Promise<[string]>;

    setTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    swap(
      _fromToken: string,
      _toToken: string,
      _fromTokenAmount: BigNumberish,
      _minReturnAmount: BigNumberish,
      _guaranteedAmount: BigNumberish,
      _referrer: string,
      _callAddresses: string[],
      _callDataConcat: BytesLike,
      _starts: BigNumberish[],
      _gasLimitsAndValues: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateReceiveAmount(
      _newReceiveAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSendAmount(
      _newSendAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addSetTokenAddress(
    _setTokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockReceiveAmount(overrides?: CallOverrides): Promise<BigNumber>;

  mockReceiveToken(overrides?: CallOverrides): Promise<string>;

  mockSendAmount(overrides?: CallOverrides): Promise<BigNumber>;

  mockSendToken(overrides?: CallOverrides): Promise<string>;

  setTokenAddress(overrides?: CallOverrides): Promise<string>;

  swap(
    _fromToken: string,
    _toToken: string,
    _fromTokenAmount: BigNumberish,
    _minReturnAmount: BigNumberish,
    _guaranteedAmount: BigNumberish,
    _referrer: string,
    _callAddresses: string[],
    _callDataConcat: BytesLike,
    _starts: BigNumberish[],
    _gasLimitsAndValues: BigNumberish[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateReceiveAmount(
    _newReceiveAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSendAmount(
    _newSendAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addSetTokenAddress(
      _setTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mockReceiveAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mockReceiveToken(overrides?: CallOverrides): Promise<string>;

    mockSendAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mockSendToken(overrides?: CallOverrides): Promise<string>;

    setTokenAddress(overrides?: CallOverrides): Promise<string>;

    swap(
      _fromToken: string,
      _toToken: string,
      _fromTokenAmount: BigNumberish,
      _minReturnAmount: BigNumberish,
      _guaranteedAmount: BigNumberish,
      _referrer: string,
      _callAddresses: string[],
      _callDataConcat: BytesLike,
      _starts: BigNumberish[],
      _gasLimitsAndValues: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateReceiveAmount(
      _newReceiveAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSendAmount(
      _newSendAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addSetTokenAddress(
      _setTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockReceiveAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mockReceiveToken(overrides?: CallOverrides): Promise<BigNumber>;

    mockSendAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mockSendToken(overrides?: CallOverrides): Promise<BigNumber>;

    setTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      _fromToken: string,
      _toToken: string,
      _fromTokenAmount: BigNumberish,
      _minReturnAmount: BigNumberish,
      _guaranteedAmount: BigNumberish,
      _referrer: string,
      _callAddresses: string[],
      _callDataConcat: BytesLike,
      _starts: BigNumberish[],
      _gasLimitsAndValues: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateReceiveAmount(
      _newReceiveAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSendAmount(
      _newSendAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSetTokenAddress(
      _setTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockReceiveAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockReceiveToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockSendAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockSendToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swap(
      _fromToken: string,
      _toToken: string,
      _fromTokenAmount: BigNumberish,
      _minReturnAmount: BigNumberish,
      _guaranteedAmount: BigNumberish,
      _referrer: string,
      _callAddresses: string[],
      _callDataConcat: BytesLike,
      _starts: BigNumberish[],
      _gasLimitsAndValues: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateReceiveAmount(
      _newReceiveAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSendAmount(
      _newSendAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
