/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type FeeStateStruct = {
  feeRecipient: string;
  maxStreamingFeePercentage: BigNumberish;
  streamingFeePercentage: BigNumberish;
  lastStreamingFeeTimestamp: BigNumberish;
};

export type FeeStateStructOutput = [string, BigNumber, BigNumber, BigNumber] & {
  feeRecipient: string;
  maxStreamingFeePercentage: BigNumber;
  streamingFeePercentage: BigNumber;
  lastStreamingFeeTimestamp: BigNumber;
};

export interface StreamingFeeModuleInterface extends utils.Interface {
  functions: {
    "accrueFee(address)": FunctionFragment;
    "controller()": FunctionFragment;
    "feeStates(address)": FunctionFragment;
    "getFee(address)": FunctionFragment;
    "initialize(address,(address,uint256,uint256,uint256))": FunctionFragment;
    "removeModule()": FunctionFragment;
    "updateFeeRecipient(address,address)": FunctionFragment;
    "updateStreamingFee(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "accrueFee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeStates", values: [string]): string;
  encodeFunctionData(functionFragment: "getFee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, FeeStateStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeRecipient",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStreamingFee",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "accrueFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeStates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStreamingFee",
    data: BytesLike
  ): Result;

  events: {
    "FeeActualized(address,uint256,uint256)": EventFragment;
    "FeeRecipientUpdated(address,address)": EventFragment;
    "StreamingFeeUpdated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeActualized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeRecipientUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StreamingFeeUpdated"): EventFragment;
}

export type FeeActualizedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { _setToken: string; _managerFee: BigNumber; _protocolFee: BigNumber }
>;

export type FeeActualizedEventFilter = TypedEventFilter<FeeActualizedEvent>;

export type FeeRecipientUpdatedEvent = TypedEvent<
  [string, string],
  { _setToken: string; _newFeeRecipient: string }
>;

export type FeeRecipientUpdatedEventFilter = TypedEventFilter<FeeRecipientUpdatedEvent>;

export type StreamingFeeUpdatedEvent = TypedEvent<
  [string, BigNumber],
  { _setToken: string; _newStreamingFee: BigNumber }
>;

export type StreamingFeeUpdatedEventFilter = TypedEventFilter<StreamingFeeUpdatedEvent>;

export interface StreamingFeeModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StreamingFeeModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accrueFee(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controller(overrides?: CallOverrides): Promise<[string]>;

    feeStates(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        feeRecipient: string;
        maxStreamingFeePercentage: BigNumber;
        streamingFeePercentage: BigNumber;
        lastStreamingFeeTimestamp: BigNumber;
      }
    >;

    getFee(_setToken: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _setToken: string,
      _settings: FeeStateStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeModule(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFeeRecipient(
      _setToken: string,
      _newFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateStreamingFee(
      _setToken: string,
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accrueFee(
    _setToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controller(overrides?: CallOverrides): Promise<string>;

  feeStates(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      feeRecipient: string;
      maxStreamingFeePercentage: BigNumber;
      streamingFeePercentage: BigNumber;
      lastStreamingFeeTimestamp: BigNumber;
    }
  >;

  getFee(_setToken: string, overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _setToken: string,
    _settings: FeeStateStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeModule(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFeeRecipient(
    _setToken: string,
    _newFeeRecipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateStreamingFee(
    _setToken: string,
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accrueFee(_setToken: string, overrides?: CallOverrides): Promise<void>;

    controller(overrides?: CallOverrides): Promise<string>;

    feeStates(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        feeRecipient: string;
        maxStreamingFeePercentage: BigNumber;
        streamingFeePercentage: BigNumber;
        lastStreamingFeeTimestamp: BigNumber;
      }
    >;

    getFee(_setToken: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _setToken: string,
      _settings: FeeStateStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    removeModule(overrides?: CallOverrides): Promise<void>;

    updateFeeRecipient(
      _setToken: string,
      _newFeeRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateStreamingFee(
      _setToken: string,
      _newFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "FeeActualized(address,uint256,uint256)"(
      _setToken?: string | null,
      _managerFee?: null,
      _protocolFee?: null
    ): FeeActualizedEventFilter;
    FeeActualized(
      _setToken?: string | null,
      _managerFee?: null,
      _protocolFee?: null
    ): FeeActualizedEventFilter;

    "FeeRecipientUpdated(address,address)"(
      _setToken?: string | null,
      _newFeeRecipient?: null
    ): FeeRecipientUpdatedEventFilter;
    FeeRecipientUpdated(
      _setToken?: string | null,
      _newFeeRecipient?: null
    ): FeeRecipientUpdatedEventFilter;

    "StreamingFeeUpdated(address,uint256)"(
      _setToken?: string | null,
      _newStreamingFee?: null
    ): StreamingFeeUpdatedEventFilter;
    StreamingFeeUpdated(
      _setToken?: string | null,
      _newStreamingFee?: null
    ): StreamingFeeUpdatedEventFilter;
  };

  estimateGas: {
    accrueFee(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<BigNumber>;

    feeStates(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getFee(_setToken: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _setToken: string,
      _settings: FeeStateStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeModule(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFeeRecipient(
      _setToken: string,
      _newFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateStreamingFee(
      _setToken: string,
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accrueFee(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeStates(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFee(
      _setToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _setToken: string,
      _settings: FeeStateStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeModule(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFeeRecipient(
      _setToken: string,
      _newFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateStreamingFee(
      _setToken: string,
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
