/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface UniswapV3MathMockInterface extends utils.Interface {
  functions: {
    "testFormatSqrtPriceX96ToPriceX96(uint160)": FunctionFragment;
    "testFormatX96ToX10_18(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "testFormatSqrtPriceX96ToPriceX96",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testFormatX96ToX10_18",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "testFormatSqrtPriceX96ToPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testFormatX96ToX10_18",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UniswapV3MathMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapV3MathMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    testFormatSqrtPriceX96ToPriceX96(
      _sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    testFormatX96ToX10_18(
      _valueX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  testFormatSqrtPriceX96ToPriceX96(
    _sqrtPriceX96: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  testFormatX96ToX10_18(
    _valueX96: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    testFormatSqrtPriceX96ToPriceX96(
      _sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testFormatX96ToX10_18(
      _valueX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    testFormatSqrtPriceX96ToPriceX96(
      _sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testFormatX96ToX10_18(
      _valueX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    testFormatSqrtPriceX96ToPriceX96(
      _sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testFormatX96ToX10_18(
      _valueX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
