import { Box, Center, Heading, List, ListItem, Text } from '@chakra-ui/react';
import React, { useMemo } from 'react';

import { YoutubeEmbed } from '../../../atoms/YoutubeEmbed';
import { DynamicGrid } from '../../../molecules/DynamicGrid';
import FeeBox from './FeeBox';
import { TokenDetailPane } from './types';

// < Embed https://www.youtube.com/watch?v=NbCayJdAR_c >
export function SwyfToken({ details, data }: TokenDetailPane): JSX.Element {
	const panels: JSX.Element[] = useMemo(
		() => [
			<Box>
				<Heading>What is the SW Yield Fund?</Heading>
				<Text>
					The SW Yield Fund is the smart way to invest in DeFi yield farms. Our team of experts
					intelligently analyzes and allocates across the best yield farms to minimize risk and
					maximize returns. With the SW Yield Fund, you can take advantage of the interest payments
					generated by yield farms while mitigating the variety of risks associated with them.
				</Text>
				<Text fontWeight={500}>
					The SW Yield Fund is a diversified fund that seeks a target return of 60% per year.
				</Text>
				<Text>
					We employ a variety of short and long-term yield farming strategies backed by machine
					learning to generate alpha for our investors. If you're looking for a smart, safe way to
					invest in DeFi yield farms, look no further than the SW Yield Fund.
				</Text>
			</Box>,
			<Box>
				<Center>
					<YoutubeEmbed embedId="NbCayJdAR_c" title={`${details?.symbol ?? 'SWYF'} token`} />
				</Center>
			</Box>,
			<Box>
				<Heading>Risk Management</Heading>
				<List>
					<ListItem>Maximum of 25% to any single DeFi protocol</ListItem>
					<ListItem>
						Maximum directional market exposure of 25% but targets zero market exposure.
					</ListItem>
					<ListItem>
						All protocols that {details?.symbol ?? 'SWYF'} is providing liquidity for are
						investigated and code-reviewed by a team of DeFi developers and quantitative analysts.
					</ListItem>
					<ListItem>Protocol insurance through Nexus Mutual and InsurAce when available</ListItem>
				</List>
				<Text>
					All protocols that {details?.symbol ?? 'SWYF'} is providing liquidity for are investigated
					and code-reviewed by a team of DeFi developers and quantitative analysts.
				</Text>
			</Box>,
			<Box>
				<Heading>Features/Benefits</Heading>
				<List>
					<ListItem>Enjoy the peace of mind that comes with being smart about your money.</ListItem>
					<ListItem>Let us take the guesswork out of finding the best yield farms.</ListItem>
					<ListItem>Sleep easy at night knowing you're intelligently diversified.</ListItem>
				</List>
			</Box>,
			<Box>
				<FeeBox symbol={details?.symbol ?? 'SWYF'} details={details} data={data} />
			</Box>,
			<Box>
				<Heading>Quarterly Lock-Up</Heading>
				<Text>
					SW Yield Funds are only available to sell out of during the final 3 days of every calendar
					quarter.
				</Text>
			</Box>,
		],
		[details, data],
	);

	return (
		<Box width="100%">
			<DynamicGrid cells={panels} width="100%" />
		</Box>
	);
}
