/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DebtIssuanceMock,
  DebtIssuanceMockInterface,
} from "../DebtIssuanceMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    gas: "0x01ba8140",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
    ],
    name: "registerToIssuanceModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
  {
    inputs: [],
    name: "removeModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
    ],
    name: "unregisterFromIssuanceModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fa806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c8063847ef08d1461005c578063c3c5a54714610066578063c4d66de8146100a0578063d9b1b6e0146100c6578063e0799620146100ec575b600080fd5b610064610112565b005b61008c6004803603602081101561007c57600080fd5b50356001600160a01b0316610114565b604080519115158252519081900360200190f35b610064600480360360208110156100b657600080fd5b50356001600160a01b0316610129565b610064600480360360208110156100dc57600080fd5b50356001600160a01b031661017f565b6100646004803603602081101561010257600080fd5b50356001600160a01b03166101a3565b565b60006020819052908152604090205460ff1681565b806001600160a01b0316630ffe0f1e6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561016457600080fd5b505af1158015610178573d6000803e3d6000fd5b5050505050565b6001600160a01b03166000908152602081905260409020805460ff19166001179055565b6001600160a01b03166000908152602081905260409020805460ff1916905556fea26469706673582212201837b2f80459689aa3e4bbf5bb04e8793507a18e6b76dc5385ef2e2e79cedb9364736f6c634300060a0033";

type DebtIssuanceMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DebtIssuanceMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DebtIssuanceMock__factory extends ContractFactory {
  constructor(...args: DebtIssuanceMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DebtIssuanceMock> {
    return super.deploy(overrides || {}) as Promise<DebtIssuanceMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DebtIssuanceMock {
    return super.attach(address) as DebtIssuanceMock;
  }
  connect(signer: Signer): DebtIssuanceMock__factory {
    return super.connect(signer) as DebtIssuanceMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DebtIssuanceMockInterface {
    return new utils.Interface(_abi) as DebtIssuanceMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DebtIssuanceMock {
    return new Contract(address, _abi, signerOrProvider) as DebtIssuanceMock;
  }
}
