/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAaveLendingPool,
  IAaveLendingPoolInterface,
} from "../IAaveLendingPool";

const _abi = [
  {
    inputs: [],
    name: "core",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    gas: "0x01ba8140",
  },
];

export class IAaveLendingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveLendingPoolInterface {
    return new utils.Interface(_abi) as IAaveLendingPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveLendingPool {
    return new Contract(address, _abi, signerOrProvider) as IAaveLendingPool;
  }
}
