/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IClearingHouseConfig,
  IClearingHouseConfigInterface,
} from "../IClearingHouseConfig";

const _abi = [
  {
    inputs: [],
    name: "getImRatio",
    outputs: [
      {
        internalType: "uint24",
        name: "imRatio",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
    gas: "0x01ba8140",
  },
];

export class IClearingHouseConfig__factory {
  static readonly abi = _abi;
  static createInterface(): IClearingHouseConfigInterface {
    return new utils.Interface(_abi) as IClearingHouseConfigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IClearingHouseConfig {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IClearingHouseConfig;
  }
}
