/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INAVIssuanceHook,
  INAVIssuanceHookInterface,
} from "../INAVIssuanceHook";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_reserveAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_reserveAssetQuantity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "invokePreIssueHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_redeemQuantity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "invokePreRedeemHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
];

export class INAVIssuanceHook__factory {
  static readonly abi = _abi;
  static createInterface(): INAVIssuanceHookInterface {
    return new utils.Interface(_abi) as INAVIssuanceHookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INAVIssuanceHook {
    return new Contract(address, _abi, signerOrProvider) as INAVIssuanceHook;
  }
}
