/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISetTokenCreator,
  ISetTokenCreatorInterface,
} from "../ISetTokenCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_components",
        type: "address[]",
      },
      {
        internalType: "int256[]",
        name: "_units",
        type: "int256[]",
      },
      {
        internalType: "address[]",
        name: "_modules",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_manager",
        type: "address",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: "0x01ba8140",
  },
];

export class ISetTokenCreator__factory {
  static readonly abi = _abi;
  static createInterface(): ISetTokenCreatorInterface {
    return new utils.Interface(_abi) as ISetTokenCreatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISetTokenCreator {
    return new Contract(address, _abi, signerOrProvider) as ISetTokenCreator;
  }
}
